"""添加外键

Revision ID: d226fe36addf
Revises: 54c2435c0371
Create Date: 2025-06-11 11:31:40.237691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd226fe36addf'
down_revision = '54c2435c0371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key('fk_post_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_post_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
